# Generated by Django 4.0.4 on 2022-04-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_parent_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Родительская категория'),
        ),
    ]
